import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import '@radix-ui/themes/styles.css';
import { ReduxProvider } from '@/providers/ReduxProviders';
import { Toaster } from 'sonner';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Vocake',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <ClerkProvider afterSignOutUrl="/sign-in">
        <html lang="en">
          <body className={`${plusJakartaSans.variable} antialiased `}>
            {children}
            <Toaster />
          </body>
        </html>
      </ClerkProvider>
    </ReduxProvider>
  );
}
